### ISSUE TITLE
Auf Seite eins werden 5 Hotelzimmer angezeigt

### ISSUE THREAD

**Issue by PushKarl** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#16]

**Comment by TaTraj** [comment]
- [x] RoomsView soll erstellt werden
- [x] soll in der NavBar als Seite aufrufbar sein
- [x] evtl. Karussel ganz oben einfügen
- [x] Hotelzimmer Cards für jedes Zimmer erstellen
- [x] Zimmerbilder in die Cards hinzufügen
- [x] Zimmernamen hinzufügen
- [x] Price per Night statisch als Placeholder für die spätere API-Daten
- [ ] Icons für die Extras statisch als Placeholder für die spätere API-Daten

**Comment by PushKarl** [comment]
soweit sind wir schon darüber hinaus. API ist angebunden, Bootstrap Icons sind da (funktionieren nur nicht.)
