### ISSUE TITLE
Bug Fix: Pagination

### ISSUE THREAD

**Issue by PushKarl** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#17]

**Comment by TaTraj** [comment]
Recommended Approach lt. Angabe:

- [ ] Verwenden Sie für die Pagination Buttons s.g. Buttongroups

**Comment by Lama500** [comment]
vue-awesome-paginate library lässt sich nicht integrieren und ich bin mit meinem Latein am Ende. Nach unzähligen Versuchen, habe ich die Pagination nun von Scratch erstellt. 

Die Komponente ist vorübergehend in die landingpage eingebaut. hier kann man mit den karten sehen, dass es funktioniert. wir können das dann in die Rooms Seite einbauen. Beim Styling scheint es noch ein Problem zu geben. Könnte auch an den Cards liegen?

**Comment by Lama500** [comment]
Das styling problem dürfte an bootstrap liegen. In der LandingPage, wenn ich b-row und b-col durch divs ersetze, dann funktioniert es ->
<div class="cards-container">
  <div v-for="card in paginatedCards" :key="card.title" class="card-wrapper">
    <HotelCard
      :title="card.title"
      :description="card.description"
      :imgSrc="card.imgSrc"
      :imgAlt="card.imgAlt"
      button-text="Verfügbarkeit prüfen"
    />
  </div>
</div>

.cards-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 10px;
}

.card-wrapper {
  width: 300px;
  margin: 10px;
}

**Comment by Lama500** [comment]
im branch pagination/marina sind die änderungen eingebunden

**Comment by TaTraj** [comment]
2 Punkte die mir bei der Pagination aufgefallen sind, die wir uns später noch überlegen könnten:

- [ ] Passt das,  wenn ich auf die zweite Seite komme, dass da noch einmal der gesamte Text von der ersten Seite steht, oder sollen nur die restlichen Zimmer angezeigt werden?
- [ ] wenn ich bei der Pagination auf "2" oder "weiter" klicke, wird zwar die Seite 2 angezeigt, aber ich bleibe ganz unten auf der Seite... evtl. könnte man da was einbauen, dass die Seite neu geladen wird oä. und man dabei wieder oben am Anfang der Seite landet - wäre "user-friendlier" 💭

**Comment by PushKarl** [comment]
Wurde in Bug Fixes übernommen
