### ISSUE TITLE
AI Bilder für Zimmer erstellen

### ISSUE THREAD

**Issue by TaTraj** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#23]
- [x] Zimmer 1 (Ric)
- [x] Zimmer 2 (Ric)
- [x] Zimmer 3 (Ric)
- [x] Zimmer  4 (Marina)
- [x] Zimmer 5 (Marina)
- [x] Zimmer 6 (Marina)
- [x] Zimmer 7 (Tamara)
- [x] Zimmer 8 (Tamara)
- [x] Zimmer 9 (Tamara)
- [x] Zimmer 10 (Tamara)

**Comment by TaTraj** [comment]
AI Bilder für Zimmer 7-10 erstellt
Bilder wurden in unserem Google Docs abgespeichert.

**Comment by PushKarl** [comment]
Bilder für Zimmer 1 Turing & Zimmer 2 Hopper generiert. Zimmer 3 Ada Lovelace war etwas sperrig und kommt noch.

**Comment by Lama500** [comment]
Ein Zimmer fehlt noch von mir. Die beiden hinzugefügten sind leider ganz anders generiert worden als bei dir Tamara :/ mehr old school als nerdy.

**Comment by TaTraj** [comment]
Ja das ist nicht so tragisch, können sie später immer noch austauschen, wenns uns nicht gefällt 😉 @Lama500
