### ISSUE TITLE
LandingView Layout verbessern

### ISSUE THREAD

**Issue by TaTraj** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#25]
- [x] Es soll statt dem Titelbild ein Karussell mit Bildern des Hotels eingebaut werden
- [x] Das Karussell soll auch in der Mobile-Ansicht vollständig und "user-friendly" angezeigt werden
- [x] Es soll eine Begrüßung eingebaut werden (Hotelname + Beschreibung/Philosophie
- [x] Die Hotelzimmer-Cards sollen umfunktioniert werden -> nur 3 nebeneinander unten klein anzeigen, welche auf die RoomsView verweisen sollen
- [ ] Evtl. Verlinkung zur Anfahrt

**Comment by PushKarl** [comment]
Müssten wir nicht eigentlich die Cards neu anlegen? Schau mal hier: [https://bootstrap-vue.org/docs/components/card#card-deck-groups](Deck Group)

**Comment by TaTraj** [comment]
Meinst du, dass die Deck Group Cards besser wären, weil sie nicht miteinander zusammen hängen aber alle gleich groß sind?

**Comment by PushKarl** [comment]
ja, da hast du nämlich nicht das Problem, dass der Text immer gleich lang sein muss. Die sind einfach in der höhe starr. Wäre eine Idee :-) Da aber diese Cards sowieso zum überarbeiten sind vom Inhalt her, dachte ich, das wäre für dich vl. interessant.
