### ISSUE TITLE
CSS Layout-Fehler beheben

### ISSUE THREAD

**Issue by TaTraj** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#26]
Durch das Entfernen der CSS-Files, haben sich einige Sachen verschoben

Folgende Sachen sollten wir anpassen:

- [x] LandingView: Abstand zwischen NavBar und Karussell einfügen
- [x] Impressum: Text soll zentriert sein
- [x] ÜberUnsView: Text ebenfalls zentrieren
- [x] RoomsView: NAvbar verdrängt Text
- [x] BookingReviewView: Tabelle nicht formatiert / Navbar verdrängt Text

**Comment by Lama500** [comment]
Das Teamfoto kann bezütlich Zuschneiden noch sehr leicht verändert werden:
object-position: 70% 30%;  ->einfach die Prozentwerte verändern

**Comment by Lama500** [comment]
Boostrap in alle drei Views integriert. kann nun leicht angepasst werden

**Comment by Lama500** [comment]
RoomsView muss auch noch bearbeitet werden!

**Comment by PushKarl** [comment]
Done
