### ISSUE TITLE
der Benutzer bekommt klares Feedback über die Verfügbarkeit in diesem Zeitraum

### ISSUE THREAD

**Issue by PushKarl** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#28]
Wenn die Buchung nicht möglich ist = "Buchung nicht möglich"
Wenn Buchung möglich => Button: Buchung abschließen

Sonst macht es mit Usecase 4 keinen Sinn. Da müssen wir nämlich dann eine Page machen, wo dann die Reservierungsdaten ausgegeben werden

**Comment by TaTraj** [comment]
- [x] Wenn ja = grünes Modal + Button auf "Buchung abschließen"
- [x] wenn nein = rotes Modal

**Comment by Lama500** [comment]
Modal ist fertig und auch schon verknüpft mit der Verfügbarkeitslogik. Je nach Auswahl des Datums erscheint das jeweilige Modal (success oder failure)
