### ISSUE TITLE
Mögliche Fehlerfälle werden abgefangen und der Benutzer entsprechend darauf hingewiesen

### ISSUE THREAD

**Issue by PushKarl** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#29]

**Comment by TaTraj** [comment]
Wird grundsätzlich mit dem Issue #28 abgedeckt
Evtl. überlegen, was passiert wenn ein falsches Datum o.Ä. eingeben wird

**Comment by Lama500** [comment]
Folgende Fehler werden abgefangen:

- [x] Enddatum kleiner als Startdatum
- [x] Falls End oder Startdatum fehlt oder beides
