### ISSUE TITLE
Der Benutzer kann zu einem gewünschten Zeitraum ein gewünschtes Zimmer unter Angabe seiner vollständigen und korrekten Daten Buchen, wenn das Zimmer verfügbar ist

### ISSUE THREAD

**Issue by PushKarl** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#31]
Also hier auch den minimalen Aufwand: Kleines Formular Buchung eingeben. Oder überhaupt als Gast zu Buchen.

**Comment by PushKarl** [comment]
Heißt eine Seite, die das Kontaktformular zeigt.

**Comment by TaTraj** [comment]
![image](https://github.com/user-attachments/assets/ec4851b5-4fb1-41d5-a158-f923c71836d1)


**Geburtsdatum bitte auch einbauen!**

**Comment by PushKarl** [comment]
Page zur Navbar hinzugefügt. Zeilen 30 bis 35
