### ISSUE TITLE
Verschiedene Bugs ausbessern

### ISSUE THREAD

**Issue by Lama500** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#36]
- [x] Pagination Ansicht auf Seite 2; Man sollte automatisch wieder an den Seitenanfang kommen
- [x] Bezeichnungen auf der Webseite sollen einheitlich sein -> z.B. in der Navbar wird zwischen Englisch und Deutsch gewechselt
- [x] NavBar soll wieder einklappen im Mobile Modus

Falls Zeit übrig ist
- [x] Im Buchungsformular wird nicht abgeprüft, ob die email adressen übereinstimmen
- [x] Im Buchungsformular wird nicht geprüft, ob das Geburtsdatum korrekt ist

**Comment by PushKarl** [comment]
Done
