### ISSUE TITLE
U5: Die Bestätigung wird mit den in der Sektion Details beschriebenen Informationen erweitert

### ISSUE THREAD

**Issue by PushKarl** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#39]
Die Details der Buchung sollen anzeigt werden:

- [x] 1. Der Zeitraum

- [ ] 2. Das Hotelzimmer inkl. Bild, Titel, Extras und Beschreibung

- [x] 3. Seine Daten, die er angegeben hat

- [x] 4. Anfahrtsbeschreibung zum Hotel, und eventuelle weiter Informationen (Zugverbindungen)

- [x] 5. Kontaktmöglichkeiten

**Comment by PushKarl** [comment]
- [x]  Die Bestätigung soll möglichst auf A4 Ausdruckbar sein (drucken aus Browser reicht, kein PDF Umwandlung nötig)

- [x] Es gibt ein klares Ergebnis zum Thema Anfahrtsplan: Umsetzung, je nach Recherche Ergebnis

**Comment by TaTraj** [comment]
Die ConfirmationView wurde durch die oben genannten Details ergänzt. Ich habe es leider nach ewigen rumprobieren nicht geschafft Punkt 2. (Hotelzimmer inkl. Bild, Titel, Extras und Beschreibung) abzurufen bzw. darzustellen. Ich pushe den Zwischenstand nun in meinen Branch "final_bookingConfirmation"

**Comment by PushKarl** [comment]
Fast Done
