### ISSUE TITLE
U5: ENDE -> V1.0.0 wurde released (tagging)

### ISSUE THREAD

**Issue by PushKarl** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#40]
Semantische Versionierung - Wie?
MAJOR.MINOR.PATCH-NAME
1. MAJOR version, wenn eine inkompatible API Änderung vorgenommen wurde
2. MINOR version, wenn Funktionalität ergänzt wurde und die Version abwärtskompatibel bleibt
3. PATCH version, wenn abwärtskompatibel Fehler ausgebessert wurden
4. NAME, ist optional und wird gerne verwendet, um Major Versions zu benennen

Die zählweise geschieht so, dass der höhere Eintrag den niedrigeren auf 0 zurücksetzt. D.h. wenn MINOR um 1 erhöht wird, wird PATCH auf 0 zurückgestellt, usw.
(https://semver.org/)

Semantische Versionierung - Beispiele

v0.1.0-beta Version 0
klassisch beginnt man eine Beta-Version mit der Major

v1.0.0-technikum 
wäre der erste Major Release, also die erste Veröffentlichung

v1.0.23-technikum 
es wurden 23 Merges in den Master durchgeführt, bei denen Fehler ausgebessert wurden

v1.2.0-technikum 
es wurden 2 Merges in den Master durchgeführt, die neue Funktionalität zum Projekt hinzugefügt haben.

v2.0.0-academy 
Es gab einen Merge mit einer so großen Veränderung, dass die Schnittstellen nicht mehr mit den vorigen kompatibel sind. Die API Doku muss upgedatet werden und alle Teilnehmer die Version 1 nutzen und auf 2 umsteigen wollen, müssen potenziell Änderungen an ihrem Code vornehmen.

**Comment by TaTraj** [comment]
Nach usecase5 --> Major Release v1.0.0-NerdHotel
Commit “Personendaten, Kontakt, Anfahrt und Maps in ConfirmationView integriert“
Hash: 3d9e78b4716de00167768896a0252c11855c160

Nach usecase6 --> Minor Version v1.2.0-NerdHotel
Commit "Registrierungsform, Store und Page" 
Hash: 397ccd04774015270580c44a5f66c0812d777a82

Nach usecase7 --> Minor Version v1.3.0-NerdHotel
Commit "Registierung nun verknüpft mit Login. Sichtbarkeit gegeben in der Nav. Reg-Form falsche Form eingaben werden nun angezeigt"
Hash: 594ccd6bf611ab1764a40fc4344e7c621aeec2ce


Finale Version: v1.3.5-NerdHotel
(Patch version)
