### ISSUE TITLE
U5: Reservierungsbestätigung verbessern

### ISSUE THREAD

**Issue by PushKarl** [Lammer-FH/academy-boutique-hotel-technikum-2024-gruppec#5]
### Als Gast möchte ich nach der Buchung erfahren, ob diese erfolgreich oder fehlerhaft war um zu wissen ob ich meinen Prozess beenden kann, oder weitere Schritte nötig sind.

**Details**

Die in U4 angesprochene Buchungsbestätigung soll erweitert werden, um den Benutzer ausführlich über alle Details zu informieren und ihm die Anreise und das Einchecken zu erleichtern.

Die Details der Buchung sollen anzeigt werden:
        1. Der Zeitraum
        2. Das Hotelzimmer inkl. Bild, Titel, Extras und Beschreibung
        3. Seine Daten, die er angegeben hat
        4. Anfahrtsbeschreibung zum Hotel, und eventuelle weiter Informationen (Zugverbindungen)
        5. Kontaktmöglichkeiten

**Recommended Approach**

- [x] Überlegen Sie welche Informationen sonst noch notwendig sind (außer hier beschriebene)
- [ ] Paperprototype der Ausgabe
- [ ] Können Komponenten wieder verwendet werden?
- [x] Kann man Google Maps oder Ähnliches einbinden für die Anfahrt? Gibt es da Packages, was benötigt man dazu?

### Important Comment
Diese Userstory markiert (wenn 1-4 auch erledigt sind) den ersten Milestone und damit ersten Release. Wir erreichen damit V1.0.0

**Definition of Done**

- [x] #39
- [x] #47
- [x] Es gibt ein klares Ergebnis zum Thema Anfahrtsplan: Umsetzung, je nach Recherche Ergebnis
- [x] Das Feature wurde in einem eigenen Branch eingecheckt und ins Git-Repository gepusht
- [ ] Das Feature wurde nach einem Code Review in den Master gemerged
- [x] #40

**Comment by TaTraj** [comment]
Hoteldaten konnten nicht im UI angezeigt werden
